openshift_version: ${ocp_version} 
vip_dhcp_allocation: false
user_managed_networking: true
password: true
base_dns_domain: ${ocp_base_domain}
network_type: Calico
pull_secret: /aicli/openshift_pull.json
installconfig:
  networking:
    networkType: Calico
    machineNetwork:
    - cidr: ${vm_private_network_ipv4_cidr}
%{ if vm_private_network_ipv6_cidr != "" }
    - cidr: ${vm_private_network_ipv6_cidr}
%{ endif }
