name: Terraform docs and formatting
on:
  pull_request_target:
    types:
      - opened
      - synchronize
      - reopened
  push:
    branches:
      - main
jobs:
  formatting:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@d632683dd7b4114ad314bca15554477dd762a938
        with:
         ref: ${{ github.event.pull_request.head.sha }}
      - name: terraform fmt
        uses: dflook/terraform-fmt-check@86914e9afad7218471018af867cc8d157d485d4b
        with:
          path: /

  docs:
    runs-on: ubuntu-22.04
    needs: formatting
    steps:
    - uses: actions/checkout@d632683dd7b4114ad314bca15554477dd762a938
      with:
        ref: ${{ github.event.pull_request.head.ref }}
    - name: Render terraform docs and push changes back to PR branch
      uses: terraform-docs/gh-actions@72ed18e5751c95dc36107dff832598081ff56eb9
      with:
        working-dir: .
        output-file: README.md
        output-method: inject
        git-push: "true"
